feat: implement generic feed content translations
acikkaynak/deprem-yardim-frontend pull request #1179
Opened 2023-02-21 18:40 UTC by oguzergul

# Description

**discord username: afetharita#0001**

**closes #1178 **

Please describe your changes. Also describe your aim and content. Do not forget to list the dependencies required caused by those changes.

## Things to check before creating a PR
- [ ] I have inspected my topic, checked.
- [ ] If it is a core feature, executed detailed tests.

## Creating PR rules
- [ ] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [ ] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [ ] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [ ] Related file selection: Only relevant files should be touched and no other files should be affected.
- [ ] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [ ] Clean commit history: The commits where the changes are made should be clear and organized.
- [ ] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [ ] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

# How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

**Test Configuration**:

* Firmware version:
* Hardware:
* Toolchain:
* SDK:

2023-02-21 19:49 UTC, sercanerhan commented
Couldn't validate the `Ahpab` with the proposed one. It should be `Ahbap Locations`.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/3420568/220443761-579774b7-317e-4491-8d1e-d33dafc5d95b.png">

2023-02-21 20:33 UTC, oguzergul commented
@sercanerhan this is draft pr :)

2023-02-21 20:36 UTC, sercanerhan commented
may bad 🤦‍♂️ @oguzergul

2023-02-21 22:51 UTC, eraygundogmus commented
@oguzergul please fix build err

2023-02-21 23:08 UTC, oguzergul commented
> @oguzergul please fix build err

fixed 👌🏼

2023-02-21 23:33 UTC, eraygundogmus requested changes

2023-02-21 23:33 UTC, eraygundogmus commented on public/locales/en/home.json
> +        "channels": {
prettierdan geçmemiş sanki

2023-02-21 23:33 UTC, eraygundogmus commented on public/locales/tr/home.json
> +            "ahbap":"Ahbap Lokasyonları",
burası da aynı şekilde prettierdan geçmemiş gibi

2023-02-21 23:36 UTC, eraygundogmus commented
++ you got conflicts

2023-02-21 23:43 UTC, usirin commented on public/locales/en/home.json
> +        "channels": {
bana da oyle geldi.

2023-02-22 00:01 UTC, oguzergul commented on public/locales/en/home.json
> +        "channels": {
.prettierignore dosyasında public klasörü ignore edilmiş. madem öyle bu dosyayı kaldırıyorum ignore dosyasyından.

2023-02-22 00:07 UTC, oguzergul commented
> ++ you got conflicts

prettier issuesundan dolayı pr ı içeri almadığımız  ve üzerine hook refactor edildiği için boru gibi conflict olmuş. elimize sağlık 🙏🏼 (well thought pros-cons)

2023-02-22 03:15 UTC, eraygundogmus commented
> > ++ you got conflicts
> 
> prettier issuesundan dolayı pr ı içeri almadığımız ve üzerine hook refactor edildiği için boru gibi conflict olmuş. elimize sağlık 🙏🏼 (well thought pros-cons)

kızdın mı :(

2023-02-22 09:31 UTC, eraygundogmus commented
@oguzergul bro? what are these conflicts? are you even a real developer?

2023-02-22 13:30 UTC, sercanerhan commented
Found `Yardım İçeriği` & `Ahbap` in channel names which are not respect to task description. Additionally, yemek icons are still different.

I've checked it since this task has the `waiting-test` label.  @oguzergul could you please guide if I need to use a different URL?

2023-02-22 19:10 UTC, sevilayerkan commented
As test team we encountered couple of problems:

1) We are getting invalid icons like in the ss
![image](https://user-images.githubusercontent.com/22706692/220731664-fedec66d-38e4-4551-b3fd-db99ae83eeb8.png)
![image](https://user-images.githubusercontent.com/22706692/220731864-46ff2e05-fb16-4737-87ab-cab6818e78a3.png)

2) We could not see any data coming from depremihtiyac.com channel

2023-02-22 19:15 UTC, oguzergul commented
> As test team we encountered couple of problems:
> 
> 1. We are getting invalid icons like in the ss
>    ![image](https://user-images.githubusercontent.com/22706692/220731664-fedec66d-38e4-4551-b3fd-db99ae83eeb8.png)
>    ![image](https://user-images.githubusercontent.com/22706692/220731864-46ff2e05-fb16-4737-87ab-cab6818e78a3.png)
> 2. We could not see any data coming from depremihtiyac.com channel

Please add the relevant test url to your comments so that we can try the same problems again. I also just threw another commit. He must have solved some of you. Can you check? @sevilayerkan

2023-02-22 19:38 UTC, sercanerhan commented
tested the deployment - Feb 22, 2023 at 7:31PM (UTC) 👍  regarding to the issues **https://github.com/acikkaynak/deprem-yardim-frontend/issues/1178 ** and **https://github.com/acikkaynak/deprem-yardim-frontend/issues/1166 **

2023-02-22 19:56 UTC, sevilayerkan commented
I added related url in comment. Also i checked again did not see first problem in the last vercel. @oguzergul

2023-02-22 19:58 UTC, oguzergul commented
depremyardim data has not any relation with this pr. am I wrong? @sercanerhan @sevilayerkan

2023-02-22 20:15 UTC, sevilayerkan commented
We checked out depremyardım datas because this pr covers the issue #1178 @oguzergul

2023-02-22 20:36 UTC, oguzergul commented
@sevilayerkan  depremihtiyac.com not returning any data yet. so it is normal to not see any value.

2023-02-22 21:27 UTC, merged