Implement filters
acikkaynak/deprem-yardim-frontend pull request #1195
Opened 2023-02-23 04:19 UTC by usirin

Fixes #1124 
Fixes #1125

2023-02-23 11:03 UTC, eraygundogmus commented on src/components/Filter/FilterControl.tsx
> +
const { name, label, value, multiple } = props

2023-02-23 11:04 UTC, eraygundogmus commented on src/components/Map/Controls/index.tsx
> +import { useServiceFilter } from "@/features/location-filters/stores/useServiceFilter";
import {  FilterDisasterVictim, FilterHelpRequest, FilterService, ...} from "features/location-filters" 

what do you think?

2023-02-23 11:14 UTC, usirin commented
forgot to add `wip` label. still in progress

2023-02-23 15:16 UTC, eraygundogmus commented
@usirin is there anything that I can help?

2023-02-23 18:44 UTC, absolutezero13 commented on src/components/Filter/Filter.tsx
> +export const Filter = (props: Props) => {
({isOpen}: Props) maybe

2023-02-24 11:27 UTC, eraygundogmus requested changes
is it still on progress? otherwise i am gonna review it

2023-02-24 22:56 UTC, usirin commented
@eraygundogmus yep it's ready

2023-02-25 11:00 UTC, eraygundogmus approved these changes
looks great. also it'd be nice if you could look for unresolved comments in this pr, but it is ok anyway

2023-02-25 21:46 UTC, merged