fix: side menu - kaynak butonu twitter yönlendirme sorunu #482
acikkaynak/deprem-yardim-frontend pull request #496
Opened 2023-02-08 17:45 UTC by bb7hn

Created types for new extra_parameters field. parsed checked and redirected url. If cannot parse or values are invalid alerted a message
- [x] Approved tagine sahip bir issue için PR açılmalıdır. Aksi takdirde PR reddedilecektir.
- [x] Açıklayıcı ve anlaşılır bir başlık: PR başlığı, değişikliklerin niteliklerini ve amaçlarını açık bir şekilde tanımlamalıdır. Pr başlığı, PR açıldığında görüntülenen ilk şey olmalıdır. Ve semantik commit kurallarını takip etmelidir. Örneğin "docs: Add README.md" şeklinde bir başlık kullanılabilir. 
- [x] İlgili issue numarası: PR ile ilgili issue numarası, PR başlığının sonuna # ile eklenmelidir.
- [x] İlgili dosya seçimi: Sadece ilgili dosyalara dokunulmalı ve başka dosyaların etkilenmemesi sağlanmalıdır.
- [x] Format ve Lint uygunluğu: Kod, belirli bir format standardına uygun hale getirilmeli ve lint kurallarına göre incelenmelidir.
- [x] Temiz commit geçmişi: Değişikliklerin yapıldığı commitler, anlaşılır ve düzenli olmalıdır.
- [x] İş tamamlandığında PR açılması: PR, iş tamamlandığında açılmalı ve diğer takım üyeleri tarafından incelenmesi için gönderilmelidir.

2023-02-08 18:02 UTC, oguzergul requested changes

2023-02-08 18:02 UTC, oguzergul commented on components/UI/Drawer/Drawer.tsx
> +          window.open(
Did you try to make this routing with next/router? window.open may cause problems.

you can use useRouter() hook.

2023-02-08 18:02 UTC, oguzergul commented on components/UI/Drawer/Drawer.tsx
> +      window.alert("kaynak açılamadı");
maybe we can handle these issues by using an alert component. Did you try that before?

2023-02-08 18:43 UTC, canumay requested changes

2023-02-08 18:43 UTC, canumay commented on utils/constants.ts
> +export const BASE_URL = "https://apigo.afetharita.com/feeds/areas";
apigo'ya degil api'ye istek atilmasi gerekiyor.

2023-02-08 18:54 UTC, oguzergul approved these changes

2023-02-08 19:01 UTC, cdagli commented on components/UI/Drawer/Drawer.tsx
> +// or
Commenti silsek?

2023-02-08 19:04 UTC, fdemir approved these changes

2023-02-08 19:05 UTC, cdagli commented on components/UI/Drawer/Drawer.tsx
> +        const extraParams = JSON.parse(source.extra_parameters);
Buraya da bir try catch koyabiliriz belki `JSON.parse` patlarsa? Catch `error` u set edebilir yine.

2023-02-08 19:09 UTC, bb7hn commented on components/UI/Drawer/Drawer.tsx
> +      if (source.channel === "twitter" && source.extra_parameters) {
ben twitter hariç bir tek telegram'ı biliyorum onu da ekleyip gönderiyorum. Telegram hariç var mı fikrim yok

2023-02-08 19:11 UTC, cdagli commented
tweet_id olmasina ragmen burasi yuklenmedi bende, sizde reproducible mi? 

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/7020369/217628588-d9d27a9a-9425-479c-be19-d69e0d512036.png">

Su linkten denedim https://deprem-yardim-frontend-git-fork-bb7hn-development-afetharita.vercel.app/#lat=37.588306281721756&lng=36.892022135531754&zoom=16.75 ?

2023-02-08 19:32 UTC, oguzergul approved these changes

2023-02-08 20:19 UTC, absolutezero13 commented on components/UI/Drawer/Drawer.tsx
> +          );
getTwitterLink tarzı bi util mi yazsak? google maps linkinde olduğu gibi

2023-02-08 20:59 UTC, bb7hn commented on components/UI/Drawer/Drawer.tsx
> +    if (error) {
@cdagli gözden kaçırmışım düzeltip pushladım

2023-02-08 21:05 UTC, cdagli commented on components/UI/Drawer/Drawer.tsx
> +    } catch (_) {
Bu sekilde de calisiyor olmasi lazim 

```suggestion
    } catch  {
```

Yalniz burada bir sikinti var. `JSON.parse("false")` `false donuyor, boolean. Ama `extraParams` type definition'a gore `undefined | ExtraParameters` olabiliyor, yani oradaki type break etmis oluyoruz aslinda. 

Bunu improve etme sansimiz var mi? False yerine `undefined` yapsak mesela? Boolean olmak zorunda mi?

2023-02-08 21:08 UTC, cdagli commented on components/UI/Drawer/Drawer.tsx
> +      if (source.channel === "twitter") {
Bu `if` condition'i 145. satirdaki ile birlestirmemiz mumkun mu?

2023-02-08 21:14 UTC, Ecancan commented on components/UI/Drawer/Drawer.tsx
> +          );
`anyuser` direkt kullanılabilinir bu arada burada. user id belirtilmeye gerek yok diye biliyorum. Önceki halide zaten bu şekilde çalışıyordu.

2023-02-08 22:14 UTC, cdagli commented
@bb7hn Bunu fix ettik mi yoksa bilerek mi yaptik ? 

<img src="https://user-images.githubusercontent.com/7020369/217663208-d92b2d47-2c91-46cc-ba1f-46d9f6905113.gif" height="550" />

2023-02-08 22:20 UTC, bb7hn commented
> @bb7hn Bunu fix ettik mi yoksa bilerek mi yaptik ?
> 
> <img alt="" height="550" src="https://user-images.githubusercontent.com/7020369/217663208-d92b2d47-2c91-46cc-ba1f-46d9f6905113.gif"> [ <img alt="217663208-d92b2d47-2c91-46cc-ba1f-46d9f6905113.gif" height="550" src="https://user-images.githubusercontent.com/7020369/217663208-d92b2d47-2c91-46cc-ba1f-46d9f6905113.gif"> ](https://user-images.githubusercontent.com/7020369/217663208-d92b2d47-2c91-46cc-ba1f-46d9f6905113.gif) [ ](https://user-images.githubusercontent.com/7020369/217663208-d92b2d47-2c91-46cc-ba1f-46d9f6905113.gif)

@cdagli  bu kısımda conditional rendering vardı RenderIf componentine çektim o kısımda condition hatalı kalmış şu an düzelttim

2023-02-08 22:30 UTC, cdagli commented on components/UI/Drawer/Drawer.tsx
> +      extraParams = JSON.parse(source.extra_parameters || "undefined");
Catch ettigimizde de `undefined` atayabilir miydik?

2023-02-08 22:30 UTC, cdagli approved these changes
@bb7hn Bir comment daha ekledim ama approve da ediyorum.

2023-02-08 22:36 UTC, bb7hn commented on components/UI/Drawer/Drawer.tsx
> +      extraParams = JSON.parse(source.extra_parameters || "undefined");
Kaynak linkine yönlendirme yaparken twitter iframe yüklenmesine rağmen link gitmiyordu.
Normalde endpointte channel gelirken açılmama sebebi channel gelmemesiymiş. o kısımda da düzenleme yapıp gönderim

2023-02-08 22:36 UTC, oguzergul approved these changes

2023-02-09 08:34 UTC, cdagli commented
@bb7hn Maalesef dun #533 yuzunden bu PR conflict oldu. Ama hala burada isimize yarayacak fixler var. Rica etsem conflicti cozup, PR'i guncelleyebilir misin?

2023-02-09 16:31 UTC, cdagli commented
PR stale oldugu icin kapatiyorum bunu https://github.com/acikkaynak/deprem-yardim-frontend/pull/589

2023-02-09 16:33 UTC, closed without merging